//go:build ignore

// gen_sijiao.go 从 Unicode Unihan 的 kFourCornerCode 字段生成 sijiao_dict.go。
//
// 用法：
//
//	# kFourCornerCode 在 Unihan_DictionaryLikeData.txt
//	curl -sL https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip -o /tmp/Unihan.zip
//	unzip -p /tmp/Unihan.zip Unihan_DictionaryLikeData.txt | grep kFourCornerCode > /tmp/sijiao.txt
//	go run internal/sijiaox/_tools/gen_sijiao.go /tmp/sijiao.txt > internal/sijiaox/sijiao_dict.go
//	gofmt -w internal/sijiaox/sijiao_dict.go
//
// 数据行为（已用 Unicode 17.0.0 实测，见设计文档）：
//   - 收录 16916 字：16767 单码、149 双码（最多 2 码，空格分隔）
//   - 格式 NNNN.N（主码 + 附号）或 NNNN（无附号）
//   - **与 gen_strokes 相反：多值必须整串保留，不能只取第一个**
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "用法: go run gen_sijiao.go <kFourCornerCode.tsv>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type entry struct {
		cp    rune
		codes string // 空格分隔的原始码串，整串保留（不截断多值）
	}
	var entries []entry
	var multi int

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// 格式: U+XXXX \t kFourCornerCode \t codes
		parts := strings.Split(line, "\t")
		if len(parts) != 3 || parts[1] != "kFourCornerCode" {
			continue
		}
		cp, err := strconv.ParseInt(strings.TrimPrefix(parts[0], "U+"), 16, 32)
		if err != nil {
			fmt.Fprintf(os.Stderr, "跳过无法解析的码点: %q\n", parts[0])
			continue
		}
		codes := strings.TrimSpace(parts[2])
		if codes == "" {
			continue
		}
		if strings.ContainsRune(codes, ' ') {
			multi++
		}
		entries = append(entries, entry{cp: rune(cp), codes: codes})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// 按码点升序，供运行时二分查找。
	sort.Slice(entries, func(i, j int) bool { return entries[i].cp < entries[j].cp })

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by internal/sijiaox/_tools/gen_sijiao.go; DO NOT EDIT.")
	fmt.Fprintln(w, "// 数据源: Unicode Unihan kFourCornerCode（Unihan_DictionaryLikeData.txt）。公开可嵌。")
	fmt.Fprintf(w, "// 共 %d 字，其中 %d 字为多值（最多 2 码，空格分隔，整串保留）。\n", len(entries), multi)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package sijiaox")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// sijiaoCP 是升序的码点表，与 sijiaoCode 一一对应，供二分查找。")
	fmt.Fprintln(w, "var sijiaoCP = []rune{")
	for i, e := range entries {
		if i%12 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "0x%X,", e.cp)
		if i%12 == 11 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// sijiaoCode[i] 是 sijiaoCP[i] 的四角号码（空格分隔的多值整串）。")
	fmt.Fprintln(w, "var sijiaoCode = []string{")
	for i, e := range entries {
		if i%8 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%q,", e.codes)
		if i%8 == 7 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")

	fmt.Fprintf(os.Stderr, "生成 %d 字（%d 多值）\n", len(entries), multi)
}
