//go:build ignore

// gen_jyutping.go 从 Unicode Unihan 的 kCantonese 字段生成 jyutping_dict.go。
//
// 用法：
//
//	# kCantonese 在 Unihan_Readings.txt（与其它读音字段共用，必须按字段名过滤）
//	curl -sL https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip -o /tmp/Unihan.zip
//	unzip -p /tmp/Unihan.zip Unihan_Readings.txt | grep kCantonese > /tmp/jyutping.txt
//	go run internal/jyutpingx/_tools/gen_jyutping.go /tmp/jyutping.txt > internal/jyutpingx/jyutping_dict.go
//	gofmt -w internal/jyutpingx/jyutping_dict.go
//
// 数据行为（已用 Unicode 17.0.0 实测，见设计文档）：
//   - 收录 29936 字，全单值（每字一个 Jyutping 主读音），字符集 a-z0-9，声调 1-6
//   - 注意注释头就是 "#\tkCantonese"：必须先跳 # 行，再按字段过滤（单靠字段过滤挡不住它）
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "用法: go run gen_jyutping.go <kCantonese.tsv>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type entry struct {
		cp      rune
		reading string
	}
	var entries []entry

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		// 先跳空行/注释头（注释头 "#\tkCantonese" 的字段名恰好也是 kCantonese）。
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// 格式: U+XXXX \t kCantonese \t reading —— 再按字段名过滤（该文件多读音字段共用）。
		parts := strings.Split(line, "\t")
		if len(parts) != 3 || parts[1] != "kCantonese" {
			continue
		}
		cp, err := strconv.ParseInt(strings.TrimPrefix(parts[0], "U+"), 16, 32)
		if err != nil {
			fmt.Fprintf(os.Stderr, "跳过无法解析的码点: %q\n", parts[0])
			continue
		}
		reading := strings.TrimSpace(parts[2])
		if reading == "" {
			continue
		}
		entries = append(entries, entry{cp: rune(cp), reading: reading})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// 按码点升序，供运行时二分查找。
	sort.Slice(entries, func(i, j int) bool { return entries[i].cp < entries[j].cp })

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by internal/jyutpingx/_tools/gen_jyutping.go; DO NOT EDIT.")
	fmt.Fprintln(w, "// 数据源: Unicode Unihan kCantonese（Unihan_Readings.txt）。公开可嵌。Jyutping 粤拼，单读音。")
	fmt.Fprintf(w, "// 共 %d 字。\n", len(entries))
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package jyutpingx")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// jyutCP 是升序的码点表，与 jyutReading 一一对应，供二分查找。")
	fmt.Fprintln(w, "var jyutCP = []rune{")
	for i, e := range entries {
		if i%12 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "0x%X,", e.cp)
		if i%12 == 11 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// jyutReading[i] 是 jyutCP[i] 的粤拼读音（Jyutping 主读音）。")
	fmt.Fprintln(w, "var jyutReading = []string{")
	for i, e := range entries {
		if i%12 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%q,", e.reading)
		if i%12 == 11 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")

	fmt.Fprintf(os.Stderr, "生成 %d 字\n", len(entries))
}
