//go:build ignore

// gen_cangjie.go 从 Unicode Unihan 的 kCangjie 字段生成 cangjie_dict.go。
//
// 用法：
//
//	# kCangjie 在 Unihan_DictionaryLikeData.txt（与 kFourCornerCode 等共用，必须按字段名过滤）
//	curl -sL https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip -o /tmp/Unihan.zip
//	unzip -p /tmp/Unihan.zip Unihan_DictionaryLikeData.txt | grep kCangjie > /tmp/cangjie.txt
//	go run internal/cangjiex/_tools/gen_cangjie.go /tmp/cangjie.txt > internal/cangjiex/cangjie_dict.go
//	gofmt -w internal/cangjiex/cangjie_dict.go
//
// 数据行为（已用 Unicode 17.0.0 实测，见设计文档）：
//   - 收录 29189 字，全单值（无空格分隔多值），码为字母串 A-Y（含 X=難，无 Z），长 1-5
//   - 直接存整串码，无需拆分
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "用法: go run gen_cangjie.go <kCangjie.tsv>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type entry struct {
		cp   rune
		code string
	}
	var entries []entry
	var maxLen int

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// 格式: U+XXXX \t kCangjie \t code —— 必须按字段名过滤（该文件多字段共用）
		parts := strings.Split(line, "\t")
		if len(parts) != 3 || parts[1] != "kCangjie" {
			continue
		}
		cp, err := strconv.ParseInt(strings.TrimPrefix(parts[0], "U+"), 16, 32)
		if err != nil {
			fmt.Fprintf(os.Stderr, "跳过无法解析的码点: %q\n", parts[0])
			continue
		}
		code := strings.TrimSpace(parts[2])
		if code == "" {
			continue
		}
		if len(code) > maxLen {
			maxLen = len(code)
		}
		entries = append(entries, entry{cp: rune(cp), code: code})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// 按码点升序，供运行时二分查找。
	sort.Slice(entries, func(i, j int) bool { return entries[i].cp < entries[j].cp })

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by internal/cangjiex/_tools/gen_cangjie.go; DO NOT EDIT.")
	fmt.Fprintln(w, "// 数据源: Unicode Unihan kCangjie（Unihan_DictionaryLikeData.txt）。公开可嵌。仓颉三代。")
	fmt.Fprintf(w, "// 共 %d 字，码最长 %d 个字母。\n", len(entries), maxLen)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package cangjiex")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// cangjieCP 是升序的码点表，与 cangjieCode 一一对应，供二分查找。")
	fmt.Fprintln(w, "var cangjieCP = []rune{")
	for i, e := range entries {
		if i%12 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "0x%X,", e.cp)
		if i%12 == 11 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// cangjieCode[i] 是 cangjieCP[i] 的仓颉字母码（单值整串）。")
	fmt.Fprintln(w, "var cangjieCode = []string{")
	for i, e := range entries {
		if i%12 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%q,", e.code)
		if i%12 == 11 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")

	fmt.Fprintf(os.Stderr, "生成 %d 字（码最长 %d）\n", len(entries), maxLen)
}
