//go:build ignore

// gen_vsop87.go 从官方 VSOP87D.ear 生成 vsop87_earth.go（地球日心黄经 L 与向径 R）。
//
// 用法：
//
//	# 官方数据在 CDS 斯特拉斯堡天文数据中心，catalog VI/81
//	curl -sSL https://cdsarc.cds.unistra.fr/ftp/cats/VI/81/VSOP87D.ear -o /tmp/VSOP87D.ear
//	go run internal/jieqix/_tools/gen_vsop87.go -in /tmp/VSOP87D.ear -cutoff 1e-8 \
//	    > internal/jieqix/vsop87_earth.go
//	gofmt -w internal/jieqix/vsop87_earth.go
//
// 文件格式（VSOP87 标准）：
//   - 表头行以 " VSOP87" 开头，含 "VARIABLE n"（1=L 2=B 3=R）与 "*T**p"（幂次）
//   - 数据行末尾三个浮点就是 A、B、C，该项 = A·cos(B + C·τ)，τ = 儒略千年数(TT)
//   - 已核对：L0 首两项 = (1.75347045673, 0, 0) 与 (0.03341656456, 4.66925680417,
//     6283.0758499914)，与 Meeus《Astronomical Algorithms》附录 III 逐位吻合
//
// 只取 L 和 R：算太阳视黄经用不到地球的日心黄纬 B（它对太阳地心黄经的影响
// 通过 β 进入，而 β 对黄经的修正含 tanβ 因子，太阳 β < 1.2″，可略）。
//
// -cutoff 是振幅截断阈值（弧度）。项数与精度的权衡靠锚点表实测二分，
// 不要凭感觉定：见 internal/jieqix/testdata/solar_terms_ut.tsv 与
// TestApparentLongitude_* 系列。参考量级：太阳每分钟走 2.46″ ≈ 1.19e-5 rad，
// 所以要 1 分钟精度，累计误差需压在 1e-5 rad 以内。
//
//	阈值    L+R 项数
//	1e-5        25
//	1e-6        67
//	1e-7       200
//	1e-8       556
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var hdrRe = regexp.MustCompile(`VARIABLE (\d).*\*T\*\*(\d)`)

func main() {
	in := flag.String("in", "", "VSOP87D.ear 路径")
	cutoff := flag.Float64("cutoff", 1e-8, "振幅截断阈值（弧度）")
	flag.Parse()
	if *in == "" {
		fmt.Fprintln(os.Stderr, "缺 -in")
		os.Exit(1)
	}

	f, err := os.Open(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	// series[variable][power] = 该幂次下的项
	series := map[int]map[int][][3]float64{1: {}, 3: {}}
	var curVar, curPow int
	var kept, total int

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, " VSOP87") {
			m := hdrRe.FindStringSubmatch(line)
			if m == nil {
				fmt.Fprintf(os.Stderr, "表头解析失败: %q\n", line)
				os.Exit(1)
			}
			curVar, _ = strconv.Atoi(m[1])
			curPow, _ = strconv.Atoi(m[2])
			continue
		}
		if _, want := series[curVar]; !want {
			continue // 跳过 VARIABLE 2 (B)
		}
		fs := strings.Fields(line)
		if len(fs) < 3 {
			continue
		}
		a, e1 := strconv.ParseFloat(fs[len(fs)-3], 64)
		b, e2 := strconv.ParseFloat(fs[len(fs)-2], 64)
		c, e3 := strconv.ParseFloat(fs[len(fs)-1], 64)
		if e1 != nil || e2 != nil || e3 != nil {
			fmt.Fprintf(os.Stderr, "数据行解析失败: %q\n", line)
			os.Exit(1)
		}
		total++
		if a < *cutoff {
			continue
		}
		kept++
		series[curVar][curPow] = append(series[curVar][curPow], [3]float64{a, b, c})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintf(w, "// Code generated by internal/jieqix/_tools/gen_vsop87.go; DO NOT EDIT.\n//\n")
	fmt.Fprintf(w, "// 源数据：VSOP87D.ear（CDS catalog VI/81，地球，日心黄道坐标，当日分点）\n")
	fmt.Fprintf(w, "// 截断阈值：%g 弧度。全量 %d 项，保留 %d 项（L 与 R，不含 B）。\n", *cutoff, total, kept)
	fmt.Fprintf(w, "// 每项形如 A·cos(B + C·τ)，τ 为自 J2000.0 起算的儒略千年数（TT）。\n//\n")
	fmt.Fprintf(w, "// 阈值不是拍的，是拿 testdata/solar_terms_ut.tsv 的 144 条锚点二分出来的。\n")
	fmt.Fprintf(w, "// 要改精度就改 -cutoff 重新生成，然后跑 TestTerms_AgainstNAOJAnchors 看误差。\n\n")
	fmt.Fprintf(w, "package jieqix\n\n")

	emit(w, "vsopL", series[1])
	fmt.Fprintln(w)
	emit(w, "vsopR", series[3])

	fmt.Fprintf(os.Stderr, "cutoff=%g  全量=%d  保留=%d\n", *cutoff, total, kept)
	for _, v := range []int{1, 3} {
		for p := 0; p <= 5; p++ {
			if n := len(series[v][p]); n > 0 {
				fmt.Fprintf(os.Stderr, "  %s%d: %d 项\n", map[int]string{1: "L", 3: "R"}[v], p, n)
			}
		}
	}
}

func emit(w *bufio.Writer, name string, byPow map[int][][3]float64) {
	maxPow := 0
	for p := range byPow {
		if p > maxPow {
			maxPow = p
		}
	}
	fmt.Fprintf(w, "var %s = [][][3]float64{\n", name)
	for p := 0; p <= maxPow; p++ {
		fmt.Fprintf(w, "\t{ // %s%d\n", strings.TrimPrefix(name, "vsop"), p)
		for _, t := range byPow[p] {
			fmt.Fprintf(w, "\t\t{%.11f, %.11f, %.11f},\n", t[0], t[1], t[2])
		}
		fmt.Fprintf(w, "\t},\n")
	}
	fmt.Fprintf(w, "}\n")
}
