//go:build ignore

// gen_strokes.go 从 Unicode Unihan 的 kTotalStrokes 字段生成 strokes_dict.go。
//
// 用法：
//
//	# kTotalStrokes 在 Unihan_IRGSources.txt（Unicode 15 起，不在 DictionaryLikeData.txt）
//	curl -sL https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip -o /tmp/Unihan.zip
//	unzip -p /tmp/Unihan.zip Unihan_IRGSources.txt | grep kTotalStrokes > /tmp/ks.txt
//	go run internal/strokesx/_tools/gen_strokes.go /tmp/ks.txt > internal/strokesx/strokes_dict.go
//	gofmt -w internal/strokesx/strokes_dict.go
//
// 数据行为（已用 Unicode 17.0.0 实测，见设计文档 Review Notes）：
//   - kTotalStrokes 现全是单值（旧的双值格式拆到了 kAlternateTotalStrokes）
//   - 实测 102998 条，最大 84 画（U+3106C），uint8 够用
//   - 输出两条排序平行 slice + 二分查找，比 103k 条 map 字面量省得多
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "用法: go run gen_strokes.go <kTotalStrokes.tsv>")
		os.Exit(2)
	}
	f, err := os.Open(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	type entry struct {
		cp rune
		n  uint8
	}
	var entries []entry
	var maxN int

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// 格式: U+XXXX \t kTotalStrokes \t N
		parts := strings.Split(line, "\t")
		if len(parts) != 3 || parts[1] != "kTotalStrokes" {
			continue
		}
		cp, err := strconv.ParseInt(strings.TrimPrefix(parts[0], "U+"), 16, 32)
		if err != nil {
			fmt.Fprintf(os.Stderr, "跳过无法解析的码点: %q\n", parts[0])
			continue
		}
		// 值现在全是单值；若将来又出现空格分隔的多值，取第一个并告警。
		val := parts[2]
		if i := strings.IndexByte(val, ' '); i >= 0 {
			fmt.Fprintf(os.Stderr, "警告: U+%X 是多值 %q，取第一个\n", cp, val)
			val = val[:i]
		}
		n, err := strconv.Atoi(val)
		if err != nil || n < 0 {
			fmt.Fprintf(os.Stderr, "跳过无法解析的画数: U+%X %q\n", cp, parts[2])
			continue
		}
		if n > 255 {
			// uint8 放不下就必须停下改类型，不能悄悄截断。
			fmt.Fprintf(os.Stderr, "错误: U+%X 画数 %d 超过 uint8 上限，需改数据类型\n", cp, n)
			os.Exit(1)
		}
		if n > maxN {
			maxN = n
		}
		entries = append(entries, entry{cp: rune(cp), n: uint8(n)})
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// 按码点升序，供运行时二分查找。
	sort.Slice(entries, func(i, j int) bool { return entries[i].cp < entries[j].cp })

	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()

	fmt.Fprintln(w, "// Code generated by internal/strokesx/_tools/gen_strokes.go; DO NOT EDIT.")
	fmt.Fprintln(w, "// 数据源: Unicode Unihan kTotalStrokes（Unihan_IRGSources.txt）。公有领域。")
	fmt.Fprintf(w, "// 共 %d 个汉字，最大 %d 画。\n", len(entries), maxN)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package strokesx")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// strokeCP 是升序的码点表，与 strokeN 一一对应，供二分查找。")
	fmt.Fprintln(w, "var strokeCP = []rune{")
	for i, e := range entries {
		if i%12 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "0x%X,", e.cp)
		if i%12 == 11 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "// strokeN[i] 是 strokeCP[i] 的笔画数。")
	fmt.Fprintln(w, "var strokeN = []uint8{")
	for i, e := range entries {
		if i%20 == 0 {
			fmt.Fprint(w, "\t")
		}
		fmt.Fprintf(w, "%d,", e.n)
		if i%20 == 19 {
			fmt.Fprintln(w)
		} else {
			fmt.Fprint(w, " ")
		}
	}
	fmt.Fprintln(w, "\n}")

	fmt.Fprintf(os.Stderr, "生成 %d 条，最大 %d 画\n", len(entries), maxN)
}
